#!/usr/bin/env bash
#transfer a file from server to local comp by scp


if [ $# -lt 3 ]
then
	echo "Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 85
fi

scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
