#!/usr/bin/env bash
#loader balancer

str="frontend app
    bind *:80
    default_backend servers
    timeout client 60s

backend servers
    timeout connect 10s
    timeout server 100s
    server web-01 100.25.158.57:80
    server web-02 34.203.75.71:80"

apt-get update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get install haproxy=2.0.\*
echo "$str" > init
haproxy -f init
