#!/usr/bin/env bash
#Displays "Best School" then "Hi" on the 9th of 10 iterations

count="0"

while [ $count -lt 10 ]
do
	echo "Best School"
	if [ "$count" -eq 8 ]
	then
		echo "Hi"
	fi
	count=$((count+1))
done
