#!/usr/bin/env bash
# setup user for nginx
useradd -m -s /bin/bash nginx
sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/listen [0-9]\+ default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
